name: gym_env
channels: [conda-forge]
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - scipy
  - opencv
  - pyqt
  - moviepy
  - matplotlib
  - ffmpeg
  - protobuf=4.25.*
  - absl-py
  - attrs
  - flatbuffers>=23
  - pyqtgraph=0.13.*
  - pip:
      - mediapipe==0.10.21
